// Contains map strings for various purposes (e.g., language codes, country codes, etc.)

export const TXT = {

    LANG: {
        en: "English",

        ar: "Arabic",
        az: "Azerbaijani",
        bg: "Bulgarian",
        ca: "Catalan, Valencian",
        cs: "Czech",
        cy: "Welsh",
        da: "Danish",
        de: "German",
        el: "Greek",
        eo: "Esperanto",
        es: "Spanish",
        et: "Estonian",
        eu: "Basque",
        fa: "Persian",
        fi: "Finnish",
        fr: "French",
        ga: "Irish",
        gd: "Gaelic",
        he: "Hebrew",
        hi: "Hindi",
        hr: "Croatian",
        hu: "Hungarian",
        hy: "Armenian",
        ia: "Interlingua",
        id: "Indonesian",
        ie: "Interlingue, Occidental",
        is: "Icelandic",
        it: "Italian",
        ja: "Japanese",
        ka: "Georgian",
        kk: "Kazakh",
        ko: "Korean",
        ku: "Kurdish",
        la: "Latin",
        lt: "Lithuanian",
        lv: "Latvian",
        mk: "Macedonian",
        mt: "Maltese",
        nl: "Dutch",
        no: "Norwegian",
        oc: "Occitan",
        pl: "Polish",
        pt: "Portuguese",
        rm: "Romansh",
        ro: "Romanian or Moldavian",
        ru: "Russian",
        sa: "Sanskrit",
        sk: "Slovak",
        sl: "Slovenian",
        sq: "Albanian",
        sr: "Serbian",
        sv: "Swedish",
        sw: "Swahili",
        th: "Thai",
        tk: "Turkmen",
        tl: "Tagalog",
        tr: "Turkish",
        tt: "Tatar",
        uk: "Ukrainian",
        uz: "Uzbek",
        vi: "Vietnamese",
        yi: "Yiddish",
        zh: "Chinese",
        und: "Undefined"
    },

LANGUAGE_TO_COUNTRY: {

    en: "GB",
    ar: "SA",
    bg: "BG",
    ca: "ES",
    cs: "CZ",
    cy: "GB",
    da: "DK",
    el: "GR",
    eo: "001",
    et: "EE",
    eu: "ES",
    fa: "IR",
    ga: "IE",
    gd: "GB",
    he: "IL",
    hy: "AM",
    ia: "001",
    ie: "001",
    ja: "JP",
    ka: "GE",
    kk: "KZ",
    ko: "KR",
    ku: "IQ",
    la: "VA",
    oc: "FR",
    pt_br: "BR",
    pt_pt: "PT",
    rm: "CH",
    sa: "IN",
    sk: "SK",
    sl: "SI",
    sq: "AL",
    sr: "RS",
    sv: "SE",
    sw: "TZ",
    tk: "TM",
    tl: "PH",
    tt: "UA",
    uk: "UA",
    vi: "VN",
    yi: "US",
    zh: "CN",
    zh_tw: "TW",

    und: "UN"
}

};